# Deploy-compose override configuration
# This file applies custom configurations to deploy-compose.yml

services:
  api:
    image: iworldpark/librechat-custom:latest # Docker Hub 이미지 사용
    env_file:
      - .env.live
    environment:
      - GOOGLE_KEY=${GOOGLE_KEY}
      - GOOGLE_MODELS=${GOOGLE_MODELS}

  mongodb:
    ports:
      - 27018:27017 

  meilisearch:
    env_file:
      - .env.live

  rag_api:
    image: ghcr.io/danny-avila/librechat-rag-api-dev:latest
    env_file:
      - .env.live
    environment:
      - EMBEDDINGS_PROVIDER=huggingface
      - HF_TOKEN=${HF_TOKEN}
    mem_limit: 3g
    cpus: 1.0