services:
  app:
    depends_on:
      - rag_api

  mongodb:
    ports:
      - 27017:27017

  vectordb:
    image: ankane/pgvector:latest
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - pgdata2:/var/lib/postgresql/data
    ports:
      - '5433:5432'

  rag_api:
    image: ghcr.io/danny-avila/librechat-rag-api-dev:latest
    restart: always
    expose:
      - 8000
    ports:
      - 8001:8000
    environment:
      - DB_HOST=vectordb
      - DB_PORT=5432
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - EMBEDDINGS_PROVIDER=huggingface
      - HF_TOKEN=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

volumes:
  pgdata2: